### ISSUE TITLE
got Unsupported operation in this provider  when call iconService.estimateStep(transaction).execute();

### ISSUE THREAD

**Issue by quango2304** [icon-project/icon-sdk-java#12]
i got this error when trying to estimate step to create deploy SCORE transaction

```
        Transaction transaction = TransactionBuilder.newBuilder()
                .nid(networkId)
                .from(fromAddress)
                .to(toAddress)
                .timestamp(new BigInteger(Long.toString(timestamp)))
                .nonce(nonce)
                .deploy(contentType, content)
                .params(params)
                .build();
        BigInteger estimatedStep = BigInteger.valueOf(100000000);
        // get an estimated step value
        try {
            estimatedStep = iconService.estimateStep(transaction).execute();
        } catch (Exception e) {
            System.out.println("RpcError: code: " + e + ", message: " + e.getMessage());
        }
```

**Comment by sink772** [comment]
Can you give more details about your test environment?
* icon-sdk-java version
* the full log messages when the exception occurs (output of printStackTrace())

**Comment by quango2304** [comment]
icon-sdk:1.0.0
testnet (nid 3)
```
E/MethodChannel#flutter_icon_network: Failed to handle method call
    java.lang.UnsupportedOperationException: Unsupported operation in this provider
        at foundation.icon.icx.transport.http.HttpProvider.request(HttpProvider.java:133)
        at foundation.icon.icx.IconService.estimateStep(IconService.java:237)
```

**Comment by sink772** [comment]
If you want to use `estimateStep()` method, you must use the following `HttpProvider` constructor.

https://www.javadoc.io/doc/foundation.icon/icon-sdk/latest/foundation/icon/icx/transport/http/HttpProvider.html#%3Cinit%3E(java.lang.String,int)

Please refer to the quick start guide.

https://github.com/icon-project/icon-sdk-java#quick-start

**Comment by quango2304** [comment]
```
OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .readTimeout(2000, TimeUnit.MILLISECONDS)
                .writeTimeout(6000, TimeUnit.MILLISECONDS)
                .build();
        iconService = new IconService(new HttpProvider(okHttpClient, domain));
```
currently, i created iconService like this, is it correct?

**Comment by sink772** [comment]
No, you must use `HttpProvider​(OkHttpClient httpClient, String uri, int version)` constructor.

**Comment by quango2304** [comment]
i'll test again, thank you
