### ISSUE TITLE
got  Method not found: Staking.balanceOf when try to check the token balance 

### ISSUE THREAD

**Issue by quango2304** [icon-project/icon-sdk-java#13]
```
foundation.icon.icx.transport.jsonrpc.RpcError: Method not found: Staking.balanceOf
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:270)
        at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:149)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at foundation.icon.icx.transport.http.HttpCall.convertResponse(HttpCall.java:82)
        at foundation.icon.icx.transport.http.HttpCall.execute(HttpCall.java:50)
```

here is my code
```
BigInteger getTokenBalance(String privateKey, String scoreAddress) throws IOException {
        Wallet wallet = KeyWallet.load(new Bytes(privateKey));
        Address tokenAddress = new Address(scoreAddress);
        String methodName = "balanceOf";
        RpcObject params = new RpcObject.Builder()
                .put("_owner", new RpcValue(wallet.getAddress()))
                .build();

        Call<RpcItem> call = new Call.Builder()
                .to(tokenAddress)
                .method(methodName)
                .params(params)
                .build();

        RpcItem result = iconService.call(call).execute();
        return result.asInteger();
    }
```

skd 1.0.0
testnet (nid3)

**Comment by quango2304** [comment]
this err happend because the score token is 0, after created a new score, this work fine
